# Stack Definition for Staging
services:
  # Redis is used to back our worker queues. It is not exposed.
  redis:
    image: redis:7.0.10-alpine3.17@sha256:0859ed47321d2d26a3f53bca47b76fb7970ea2512ca3a379926dc965880e442e
    volumes:
      - redis-data:/data
    deploy:
      placement:
        # We run the redis instance on the manager node only
        constraints: [node.role == manager]
    logging:
      # Use journald log driver, see:
      # https://docs.docker.com/config/containers/logging/journald/
      driver: journald
      options:
        tag: redis

  mycustomdomain:
    # Staging runs the most recent commit on the main branch
    image: ghcr.io/developingspace/starchart:main
    depends_on:
      - redis
    ports:
      - 8080:8080
    environment:
      # If the database needs to be wiped and (re)setup, add this
      #- DATABASE_SETUP=1
      - APP_URL=https://mycustomdomain-dev.senecacollege.ca
      - AWS_ROUTE53_HOSTED_ZONE_ID=Z009022527TSGPKQVW5KF
      - LETS_ENCRYPT_ACCOUNT_EMAIL=mycustomdomain-dev@senecacollege.ca
      - LETS_ENCRYPT_DIRECTORY_URL=https://acme-staging-v02.api.letsencrypt.org/directory
      - LOG_LEVEL=info
      - NODE_ENV=production
      - NOTIFICATIONS_EMAIL_USER=mycustomdomain-dev@senecacollege.ca
      - PORT=8080
      - REDIS_URL=redis://redis:6379
      - ROOT_DOMAIN=stage.mystudentproject.ca
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - DATABASE_URL
      - LETS_ENCRYPT_ACCOUNT_PRIVATE_KEY_PEM
      - NOTIFICATIONS_USERNAME
      - NOTIFICATIONS_PASSWORD
      - SESSION_SECRET
    deploy:
      mode: replicated
      replicas: 2
      rollback_config:
        # Rollback all containers at once if a deploy fails
        parallelism: 0
        failure_action: rollback
      update_config:
        # Update both containers at once, rollback on failure
        parallelism: 2
        failure_action: rollback
    logging:
      # Use journald log driver, see:
      # https://docs.docker.com/config/containers/logging/journald/
      driver: journald
      options:
        tag: mycustomdomain

secrets:
  AWS_ACCESS_KEY_ID:
    external: true
  AWS_SECRET_ACCESS_KEY:
    external: true
  DATABASE_URL:
    external: true
  LETS_ENCRYPT_ACCOUNT_PRIVATE_KEY_PEM:
    external: true
  NOTIFICATIONS_USERNAME:
    external: true
  NOTIFICATIONS_PASSWORD:
    external: true
  SESSION_SECRET:
    external: true

volumes:
  redis-data:
