import { ChakraProvider } from '@chakra-ui/react';
import { json } from '@remix-run/node';
import {
  Links,
  LiveReload,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
  useLoaderData,
} from '@remix-run/react';

import { getUser } from './session.server';
import theme from './theme';
import { addReconcilerJob } from './queues/reconciler/reconciler-queue.server';

import type { MetaFunction, LoaderArgs, LinksFunction } from '@remix-run/node';

export const meta: MetaFunction = () => ({
  charset: 'utf-8',
  title: 'My.Custom.Domain',
  description: 'Simple, Secure DNS Records and SSL Certificates for Seneca',
  viewport: 'width=device-width,initial-scale=1',
});

export const links: LinksFunction = () => [
  // We want html and body to occupy the full window height for vertical centering
  { rel: 'stylesheet', href: '/styles.css' },
  { rel: 'icon', href: '/favicon.ico', sizes: 'any' },
  { rel: 'manifest', href: '/manifest.json' },
];

export async function loader({ request, context }: LoaderArgs) {
  return json({
    user: await getUser(request),
    nonce: context.nonce as string,
  });
}

addReconcilerJob();

function Document({ children }: { children: React.ReactNode }) {
  // We need the nonce generated by the server via helmetjs to put on scripts
  const { nonce } = useLoaderData<typeof loader>();

  return (
    <html lang="en-CA">
      <head>
        <Meta />
        <Links />
      </head>
      <body>
        {children}
        <ScrollRestoration nonce={nonce} />
        <Scripts nonce={nonce} />
        <LiveReload nonce={nonce} />
      </body>
    </html>
  );
}

export default function App() {
  return (
    <Document>
      <ChakraProvider theme={theme}>
        <Outlet />
      </ChakraProvider>
    </Document>
  );
}
