name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install node modules
        run: npm ci
      - name: npm build
        run: npm run build
      - name: npm test
        run: npm test
      - name: Prettier check
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --check .
      - name: eslint check
        run: |
          # have to install eslint here for some reason... Other wise eslint wont be found
          npm install -D eslint
          npm run lint
      - run: npm run typecheck
